"""add version column to users

Revision ID: bf7ed5572946
Revises: e08583312d2a
Create Date: 2026-03-08 20:51:13.667949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7ed5572946'
down_revision: Union[str, Sequence[str], None] = 'e08583312d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('version', sa.Uuid(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.alter_column('users', 'version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'version')
    # ### end Alembic commands ###
